### ISSUE TITLE
发现一个严重的bug

### ISSUE THREAD

**Issue by a303557339** [gorkys/vue-draggable-resizable#3]
当 父子组件嵌套时，如 
<vue-draggable-resizable
        :snap="true"
        :snap-tolerance="20"
        :w="400"
        :h="400"
        :is-conflict-check="true"
        style="background: black">
        <vue-draggable-resizable
          parent="true">
          <p
            style="height:100%;width:100%;background:red">这是导航</p></vue-draggable-resizable>
      </vue-draggable-resizable>
把父组件高度缩小到比较小时，再拖动子组件，子组件会自动变成父组件的高度。

**Comment by gorkys** [comment]
是否有场景可供查看。或者在线代码。

**Comment by bolingsun** [comment]
这个在原组件上添加的元素对齐功能非常好。点赞！！！
不过，刚刚对比原生的时候，发现一个bug。draggable组件中包含input输入框元素的时候，能聚焦，但是不能输入。而原生的是可以使用input输入框的。
