### ISSUE TITLE
能否支持旋转

### ISSUE THREAD

**Issue by zc20081989** [gorkys/vue-draggable-resizable#4]

**Comment by gorkys** [comment]
@zc20081989 https://github.com/tmrcui/vue-draggable-resizable-rotatable
这有一个修改版专门针对旋转的

**Comment by zc20081989** [comment]
thanks 
------------------



卓超
星爵互动


 联系我









 




------------------ 原始邮件 ------------------
发件人: "Gorkys"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 下午5:16
收件人: "gorkys/vue-draggable-resizable"<vue-draggable-resizable@noreply.github.com>; 
抄送: "踏浪"<819101592@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [gorkys/vue-draggable-resizable] 能否支持旋转 (#4)




@zc20081989 https://github.com/tmrcui/vue-draggable-resizable-rotatable
 这有一个修改版专门针对旋转的
