### ISSUE TITLE
这个组件不错！发现了一个bug.

### ISSUE THREAD

**Issue by bolingsun** [gorkys/vue-draggable-resizable#5]
这个在原组件上添加的元素对齐功能非常好。点赞！！！
不过，刚刚对比原生的时候，发现一个bug。draggable组件中包含input输入框元素的时候，能聚焦，但是不能输入。而原生的是可以使用input输入框的。

**Comment by gorkys** [comment]
@bolingsun 我想是原版组件在重构后添加的新功能，此版本是基于1.x版本进行的修改，目前看来是需要在2.0版本中进行修改了。

**Comment by bolingsun** [comment]
@gorkys 原来如此。不过添加这个碰撞对齐的功能真的是非常好用。

**Comment by gorkys** [comment]
@bolingsun 可惜原作者并不打算支持组件与组件之间的相关功能。

**Comment by gorkys** [comment]
@bolingsun 一个好消息，我今天把2.0版的修改了。
你把之前的版本卸载掉，然后重新安装`npm install vue-draggable-resizable-gorkys`

**Comment by bolingsun** [comment]
厉害了，兄弟！我以为你暂时没有更新计划，今天我在2.0上面，按照你的思路，改了一个版本。不过你现在改过了，就可以直接npm安装使用，nice ！

**Comment by gorkys** [comment]
@bolingsun 以前有打算过更新，当时改了会儿没有思路就耽搁了，
哈哈，我重新创建了一个[仓库](https://github.com/gorkys/vue-draggable-resizable-gorkys)，允许你点第一个Star.
