### ISSUE TITLE
您好！请教一个问题，组件样式希望是position:'absolute'，但现在组件样式是transform

### ISSUE THREAD

**Issue by txlwll** [gorkys/vue-draggable-resizable#7]
![image](https://user-images.githubusercontent.com/18171146/83241698-cdb85a00-a1cd-11ea-922a-d068aa6ae8b4.png)
组件样式是希望是定位的，现在变成了如上图的transform；
希望是如下图绝对定位：
![image](https://user-images.githubusercontent.com/18171146/83241843-05270680-a1ce-11ea-9df6-776573381841.png)

**Comment by gorkys** [comment]
是的，原组件对定位进行了改变，貌似这样的性能会更好一些。如果必须`position:'absolute'`可以选择回退一个版本。
如果是因为版本升级导致原来项目的一些样式损坏了，就需要修改一下，或者指定版本。

**Comment by txlwll** [comment]
您好！除了锁定版本之外，还可以通过修改哪些样式或者配置来实现新添加的图表可以随意拖动吗，现在后面添加的图表在y轴上拖动的范围不能超过前面添加组件的y轴，如下图中的容器2纵向拖动最高不能超过容器1的高度
![image](https://user-images.githubusercontent.com/18171146/83246346-91d4c300-a1d4-11ea-8ba8-46be282e95ea.png)

**Comment by gorkys** [comment]
如果只是如图，没有其它特殊功能导致这个问题的话，我想是因为其代码问题吧，更新版本后，可参考原组件的demo链接，不会出现所述问题。另：可以进交流群里面交流，发代码截图比较方便，在新仓库里面有群号。
